<a href="https://colab.research.google.com/github/jlsrj760/myworks/blob/main/placement_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Finding Placement Status

In [ ]:
#Impoerting Library
import pandas as pd
from sklearn.model_selection import train_test_split
#ML algorithh KNN
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report

In [ ]:
#ML Algorithm
from sklearn.ensemble import AdaBoostClassifier

In [ ]:
#importing Data Set
df = pd.read_csv('/content/01 Train Data.csv')

In [ ]:
#converting traing data sets status into Binary Values
df['Placement Status 0 or 1'] = df['Placement Status'].map({'Placed': int(0), 'Not placed': int(1)})
df['Placement Status 0 or 1'] = df['Placement Status 0 or 1'].apply(lambda x: 1 if x > 0 else 0)
df.tail()

,First Name,Email ID,Quantity,Price Tier,Ticket Type,Attendee #,Group,Order Type,Currency,Total Paid,...,College Name,How did you come to know about this event?,"Specify in ""Others"" (how did you come to know about this event)",Designation,Year of Graduation,CGPA,Speaking Skills,ML Knowledge,Placement Status,Placement Status 0 or 1
4889,Saif ali,saifali@xyz.com,1,NaN,Data Visualization using Power BI,1.949319e+09,NaN,Free Order,USD,0,...,"mit academy of engineering ,alandi",NaN,NaN,Students,2021,9.0,3,2,NaN,0
4890,Lankesh,lankesh@xyz.com,1,NaN,Data Visualization using Power BI,1.949328e+09,NaN,Free Order,USD,0,...,a. c. patil college of engineering,NaN,NaN,Students,2021,7.2,4,3,NaN,0
4891,Sanjay,sanjay@xyz.com,1,NaN,Data Visualization using Power BI,1.949328e+09,NaN,Free Order,USD,0,...,wilson college,NaN,NaN,Students,2021,8.5,2,3,NaN,0
4892,Sushmita,sushmita@xyz.com,1,NaN,Data Visualization using Power BI,1.949330e+09,NaN,Free Order,USD,0,...,"ld college of engineering, ahmedabad, gujarat",NaN,NaN,Students,2021,6.5,5,5,NaN,0
4893,Vipul,vipul@xyz.com,1,NaN,Data Visualization using Power BI,1.949332e+09,NaN,Free Order,USD,0,...,dkte society's textile and engineering institu...,NaN,NaN,Students,2021,6.6,4,5,NaN,0

In [ ]:
#Selecting Features
selected_features = ['CGPA', 'Speaking Skills', 'ML Knowledge']

In [ ]:
X = df[selected_features]
y = df['Placement Status 0 or 1']

In [ ]:
#Creating data set for training and testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [299]:
model  =    KNeighborsClassifier(n_neighbors=3)

In [ ]:
model =  AdaBoostClassifier(n_estimators=50, random_state=42)

In [300]:
#Training and Testing model
model.fit(X_train,y_train)
predictions = model.predict(X_test)

AdaBoostClassifier(random_state=42)

In [302]:
#checking Accuracy of the modl
accuracy = accuracy_score(y_test, predictions)
print(f'Accuracy: {accuracy:.2f}')

Accuracy: 1.00

#Test DATA

In [ ]:
#importing Dataset
df = pd.read_csv('/content/01 Train Data.csv')

In [ ]:
#feature Selection
selected_features1 = ['CGPA', 'Speaking Skills', 'ML Knowledge']
X = Df[selected_features1]

In [303]:
#Testing
Df['Placement Status'] = model.predict(X)

In [304]:
Df.head()

,First Name,Email ID,Quantity,Price Tier,Ticket Type,Attendee #,Group,Order Type,Currency,Total Paid,...,Attendee Status,College Name,How did you come to know about this event?,"Specify in ""Others"" (how did you come to know about this event)",Designation,Year of Graduation,CGPA,Speaking Skills,ML Knowledge,Placement Status
0,Sahil,sahil@xyz.com,1,NaN,Hello ML and DL,2.293940e+09,NaN,Free Order,USD,0,...,Attending,"symbiosis institute of technology, pune",Whatsapp,NaN,Students,NaN,7.8,3,3,1
1,Amrita,amrita@xyz.com,1,NaN,Hello ML and DL,2.293941e+09,NaN,Free Order,USD,0,...,Attending,"mit academy of engineering ,alandi",Whatsapp,NaN,Students,NaN,9.1,3,3,0
2,Mamta,mamta@xyz.com,1,NaN,Hello ML and DL,2.293941e+09,NaN,Free Order,USD,0,...,Attending,a. c. patil college of engineering,Whatsapp,NaN,Students,NaN,6.9,2,2,0
3,Bhagyashri,bhagyashri@xyz.com,1,NaN,Hello ML and DL,2.293946e+09,NaN,Free Order,USD,0,...,Attending,wilson college,Others,NaN,Students,NaN,8.4,4,4,1
4,Divyanshu,divyanshu@xyz.com,1,NaN,Hello ML and DL,2.293956e+09,NaN,Free Order,USD,0,...,Attending,"ld college of engineering, ahmedabad, gujarat",Whatsapp,NaN,Students,NaN,6.7,5,5,1

In [305]:
Df['Placement Status'] = Df['Placement Status'].map({0: 'Placed', 1:  'Not placed'})
#df['Placement Status 0 or 1'] = df['Placement Status 0 or 1'].apply(lambda x: 1 if x > 0 else 0)
Df.head()

,First Name,Email ID,Quantity,Price Tier,Ticket Type,Attendee #,Group,Order Type,Currency,Total Paid,...,Attendee Status,College Name,How did you come to know about this event?,"Specify in ""Others"" (how did you come to know about this event)",Designation,Year of Graduation,CGPA,Speaking Skills,ML Knowledge,Placement Status
0,Sahil,sahil@xyz.com,1,NaN,Hello ML and DL,2.293940e+09,NaN,Free Order,USD,0,...,Attending,"symbiosis institute of technology, pune",Whatsapp,NaN,Students,NaN,7.8,3,3,Not placed
1,Amrita,amrita@xyz.com,1,NaN,Hello ML and DL,2.293941e+09,NaN,Free Order,USD,0,...,Attending,"mit academy of engineering ,alandi",Whatsapp,NaN,Students,NaN,9.1,3,3,Placed
2,Mamta,mamta@xyz.com,1,NaN,Hello ML and DL,2.293941e+09,NaN,Free Order,USD,0,...,Attending,a. c. patil college of engineering,Whatsapp,NaN,Students,NaN,6.9,2,2,Placed
3,Bhagyashri,bhagyashri@xyz.com,1,NaN,Hello ML and DL,2.293946e+09,NaN,Free Order,USD,0,...,Attending,wilson college,Others,NaN,Students,NaN,8.4,4,4,Not placed
4,Divyanshu,divyanshu@xyz.com,1,NaN,Hello ML and DL,2.293956e+09,NaN,Free Order,USD,0,...,Attending,"ld college of engineering, ahmedabad, gujarat",Whatsapp,NaN,Students,NaN,6.7,5,5,Not placed

In [307]:
Df.to_csv('my_dataset.csv', index=False)